path:
  colab: "/content/drive/MyDrive/Colab_Notebooks/Boost Camp AI Tech/Text Sentimental Classification"

wandb:
  project: "Text Sentimental Classification"
  notes: "test"
  name: "test"

model:
  name: "klue/bert-base"     # 사용 가능한 모델: klue/roberta-base, klue/bert-base, kykim/bert-kor-base, beomi/kcbert-base, monologg/koelectra-base-v3-discriminator
  num_classes: 4
  hidden_dropout: 0.1
  atten_dropout: 0.1
  classifier_dropout: 0.3
  class_label:
  - 0
  - 1
  - 2
  - 3
  
  use_LoRA: false        # "query", "key", "value", "dense"
  r: 16
  lora_alpha: 32
  target_modules:
    - "query"
    - "value"
  lora_dropout: 0.1
  bias: "none"


train:
  epoch: 4               
  batch_size: 32         
  num_workers: 6         
  mixed_precision: true  
  gradient_accum: 1      

valid:
  epoch: 1               
  batch_size: 128        
  num_workers: 6         

optimizer:
  name: "adamW"          
  learning_rate: 2e-5    
  weight_decay: 1e-2     

scheduler:
  linear:                
    use: true            
    warmup_epoch: 1      

  cosine:                
    anneal: true         
    restart: false       
    eta_min: 1e-6        
    period: 3            

loss:
  ce:
    use: true

  class_weight_ce:
    use: false

  smooth_ce:
    use: false
    smooth: 0.1

  class_weight_smooth_ce:
    use: false
    smooth: 0.1

  focal:
    use: false
    alpha: 0.25
    gamma: 2

  smooth_focal:
    use: false
    alpha: 0.25
    gamma: 2
    smooth: 0.1

  focal_class_weight:
    use: false
    gamma: 2

  smooth_focal_class_weight:
    use: false
    gamma: 2
    smooth: 0.1

tokenizer:
  max_length: 64

  new_tokens:
    - 'oo'
    - 'ㅠ'
    - 'ㅠㅠ'
    - 'ㅡㅡ'
    - 'ㅡㅅㅡ'
    - 'ㅗ'
    - '^^'
    - '♥'
    - '막장'
    - '씨발'
    - '용두사미'
    - '망작'
    - '걸작'
    - '꿀잼'
    - '노잼'
    - '오열'
    - '남주'

  special_tokens:
  - '[neg_ex]' 

seed: 13
